language: objective-c
xcode_project: CleanroomBridging.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

script:
- set -o pipefail && xcodebuild -project CleanroomBridging.xcodeproj -scheme CleanroomBridging-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomBridging.xcodeproj -scheme CleanroomBridging-OSX -destination 'platform=macOS' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomBridging.xcodeproj -scheme CleanroomBridging-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomBridging.xcodeproj -scheme CleanroomBridging-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' clean build | xcpretty
